PGOImagePrefix:  crunchydata
PGOImageTag:  centos7-4.2.3
DbDatabase:  userdb
DbUser:  postgres
DbPort:  5432
TableToLoad:  JSON_COLLECTION
FilePath:  sample.json
FileType:  json
PVCName:  csv-pvc
FSGroup:
SupplementalGroup:
