COImagePrefix:  crunchydata
COImageTag:  rhel7-3.4.0-rc2
DbDatabase:  userdb
DbUser:  postgres
DbPort:  5432
TableToLoad:  JSON_COLLECTION
FilePath:  sample.json
FileType:  json
PVCName:  csv-pvc
SecurityContext:  
