PGOImagePrefix:  registry.developers.crunchydata.com/crunchydata
PGOImageTag:  centos7-4.4.2
DbDatabase:  userdb
DbUser:  postgres
DbPort:  5432
TableToLoad:  JSON_COLLECTION
FilePath:  sample.json
FileType:  json
PVCName:  csv-pvc
FSGroup:
SupplementalGroup:
