PGOImagePrefix:  registry.developers.crunchydata.com/crunchydata
PGOImageTag:  centos7-4.3.4
DbDatabase:  userdb
DbUser:  postgres
DbPort:  5432
TableToLoad:  xraycsvtable
FilePath:  sample.csv
FileType:  csv
PVCName:  csv-pvc
FSGroup:  26
SecurityContext:
