apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "postgres-operator.fullname" . }}-cm
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "postgres-operator.labels" . | indent 4 }}
data:
  values.yaml: |
    ---
    archive_mode: "{{ .Values.archive_mode}}"
    archive_timeout: "{{ .Values.archive_timeout}}"
    backrest_aws_s3_bucket: "{{ .Values.backrest_aws_s3_bucket}}"
    backrest_aws_s3_endpoint: "{{ .Values.backrest_aws_s3_endpoint}}"
    backrest_aws_s3_key: "{{ .Values.backrest_aws_s3_key}}"
    backrest_aws_s3_region: "{{ .Values.backrest_aws_s3_region}}"
    backrest_aws_s3_secret: "{{ .Values.backrest_aws_s3_secret}}"
    backrest_aws_s3_uri_style: "{{ .Values.backrest_aws_s3_uri_style }}"
    backrest_aws_s3_verify_tls: "{{ .Values.backrest_aws_s3_verify_tls }}"
    backrest_port: "{{ .Values.backrest_port}}"
    badger: "{{ .Values.badger}}"
    ccp_image_prefix: "{{ .Values.ccp_image_prefix}}"
    ccp_image_pull_secret: "{{ .Values.ccp_image_pull_secret}}"
    ccp_image_pull_secret_manifest: "{{ .Values.ccp_image_pull_secret_manifest}}"
    ccp_image_tag: "{{ .Values.ccp_image_tag}}"
    create_rbac: "{{ .Values.create_rbac}}"
    crunchy_debug: "{{ .Values.crunchy_debug}}"
    db_name: "{{ .Values.db_name}}"
    db_password_age_days: "{{ .Values.db_password_age_days}}"
    db_password_length: "{{ .Values.db_password_length}}"
    db_port: "{{ .Values.db_port}}"
    db_replicas: "{{ .Values.db_replicas}}"
    db_user: "{{ .Values.db_user}}"
    default_instance_memory: "{{ .Values.default_instance_memory}}"
    default_pgbackrest_memory: "{{ .Values.default_pgbackrest_memory}}"
    default_pgbouncer_memory: "{{ .Values.default_pgbouncer_memory}}"
    delete_metrics_namespace: "{{ .Values.delete_metrics_namespace}}"
    delete_operator_namespace: "{{ .Values.delete_operator_namespace}}"
    delete_watched_namespaces: "{{ .Values.delete_watched_namespaces}}"
    disable_auto_failover: "{{ .Values.disable_auto_failover}}"
    disable_fsgroup: "{{ .Values.disable_fsgroup}}"
    reconcile_rbac: "{{ .Values.reconcile_rbac}}"
    exporterport: "{{ .Values.exporterport}}"
    metrics: "{{ .Values.metrics}}"
    namespace: "{{ .Values.namespace}}"
    namespace_mode: "{{ .Values.namespace_mode}}"
    pgbadgerport: "{{ .Values.pgbadgerport}}"
    pgo_add_os_ca_store: "{{ .Values.pgo_add_os_ca_store}}"
    pgo_admin_password: "{{ .Values.pgo_admin_password}}"
    pgo_admin_perms: "{{ .Values.pgo_admin_perms}}"
    pgo_admin_role_name: "{{ .Values.pgo_admin_role_name}}"
    pgo_admin_username: "{{ .Values.pgo_admin_username}}"
    pgo_apiserver_port: "{{ .Values.pgo_apiserver_port}}"
    pgo_apiserver_url: "{{ .Values.pgo_apiserver_url}}"
    pgo_client_cert_secret: "{{ .Values.pgo_client_cert_secret}}"
    pgo_client_container_install: "{{ .Values.pgo_client_container_install}}"
    pgo_client_version: "{{ .Values.pgo_client_version}}"
    pgo_cluster_admin: "{{ .Values.pgo_cluster_admin}}"
    pgo_disable_eventing: "{{ .Values.pgo_disable_eventing}}"
    pgo_disable_tls: "{{ .Values.pgo_disable_tls}}"
    pgo_image_prefix: "{{ .Values.pgo_image_prefix}}"
    pgo_image_pull_secret: "{{ .Values.pgo_image_pull_secret}}"
    pgo_image_pull_secret_manifest: "{{ .Values.pgo_image_pull_secret_manifest}}"
    pgo_image_tag: "{{ .Values.pgo_image_tag}}"
    pgo_installation_name: "{{ .Values.pgo_installation_name}}"
    pgo_noauth_routes: "{{ .Values.pgo_noauth_routes}}"
    pgo_operator_namespace: "{{ .Values.pgo_operator_namespace}}"
    pgo_tls_ca_store: "{{ .Values.pgo_tls_ca_store}}"
    pgo_tls_no_verify: "{{ .Values.pgo_tls_no_verify}}"
    pod_anti_affinity: "{{ .Values.pod_anti_affinity}}"
    pod_anti_affinity_pgbackrest: "{{ .Values.pod_anti_affinity_pgbackrest}}"
    pod_anti_affinity_pgbouncer: "{{ .Values.pod_anti_affinity_pgbouncer}}"
    scheduler_timeout: "{{ .Values.scheduler_timeout}}"
    service_type: "{{ .Values.service_type}}"
    sync_replication: "{{ .Values.sync_replication}}"
    backrest_storage: "{{ .Values.backrest_storage}}"
    backup_storage: "{{ .Values.backup_storage}}"
    primary_storage: "{{ .Values.primary_storage}}"
    replica_storage: "{{ .Values.replica_storage}}"
    wal_storage: "{{ .Values.wal_storage}}"
    storage1_name: "{{ .Values.storage1_name}}"
    storage1_access_mode: "{{ .Values.storage1_access_mode}}"
    storage1_size: "{{ .Values.storage1_size}}"
    storage1_type: "{{ .Values.storage1_type}}"
    storage2_name: "{{ .Values.storage2_name}}"
    storage2_access_mode: "{{ .Values.storage2_access_mode}}"
    storage2_size: "{{ .Values.storage2_size}}"
    storage2_type: "{{ .Values.storage2_type}}"
    storage3_name: "{{ .Values.storage3_name}}"
    storage3_access_mode: "{{ .Values.storage3_access_mode}}"
    storage3_size: "{{ .Values.storage3_size}}"
    storage3_type: "{{ .Values.storage3_type}}"
    storage3_supplemental_groups: "{{ .Values.storage3_supplemental_groups}}"
    storage4_name: "{{ .Values.storage4_name}}"
    storage4_access_mode: "{{ .Values.storage4_access_mode}}"
    storage4_size: "{{ .Values.storage4_size}}"
    storage4_match_labels: "{{ .Values.storage4_match_labels}}"
    storage4_type: "{{ .Values.storage4_type}}"
    storage4_supplemental_groups: "{{ .Values.storage4_supplemental_groups}}"
    storage5_name: "{{ .Values.storage5_name}}"
    storage5_access_mode: "{{ .Values.storage5_access_mode}}"
    storage5_size: "{{ .Values.storage5_size}}"
    storage5_type: "{{ .Values.storage5_type}}"
    storage5_class: "{{ .Values.storage5_class}}"
    storage6_name: "{{ .Values.storage6_name}}"
    storage6_access_mode: "{{ .Values.storage6_access_mode}}"
    storage6_size: "{{ .Values.storage6_size}}"
    storage6_type: "{{ .Values.storage6_type}}"
    storage6_class: "{{ .Values.storage6_class}}"
    storage7_name: "{{ .Values.storage7_name}}"
    storage7_access_mode: "{{ .Values.storage7_access_mode}}"
    storage7_size: "{{ .Values.storage7_size}}"
    storage7_type: "{{ .Values.storage7_type}}"
    storage7_class: "{{ .Values.storage7_class}}"
    storage8_name: "{{ .Values.storage8_name}}"
    storage8_access_mode: "{{ .Values.storage8_access_mode}}"
    storage8_size: "{{ .Values.storage8_size}}"
    storage8_type: "{{ .Values.storage8_type}}"
    storage8_class: "{{ .Values.storage8_class}}"
    storage9_name: "{{ .Values.storage9_name}}"
    storage9_access_mode: "{{ .Values.storage9_access_mode}}"
    storage9_size: "{{ .Values.storage9_size}}"
    storage9_type: "{{ .Values.storage9_type}}"
    storage9_class: "{{ .Values.storage9_class}}"
