[[constraint]]
  name = "github.com/evanphx/json-patch"
  version = "4.6.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.9.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.4"

[[constraint]]
  name = "github.com/nsqio/go-nsq"
  version = "1.0.8"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "3.0.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.5"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.8"

[[constraint]]
  name = "k8s.io/api"
  version = "0.17.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "0.17.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "0.17.3"

# The following override is for generating the docs using the
# "generatedocs" program in pgo
[[override]]
  name = "github.com/russross/blackfriday"
  version = "1.5.2"

[prune]
  go-tests = true
  unused-packages = true
