[[constraint]]
name = "k8s.io/apimachinery"
version = "kubernetes-1.9.0"

[[constraint]]
name = "k8s.io/client-go"
version = "6.0.0"

[[constraint]]
name = "k8s.io/api"
version = "kubernetes-1.9.0"

[[constraint]]
  name = "github.com/nsqio/go-nsq"
  version = "v1.0.7"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.4.0"

[[override]]
  name = "gopkg.in/yaml.v2"
  version = ">=v2.2.3" # < 2.2.3 has a DoS vuln

[[constraint]]
  name = "gopkg.in/robfig/cron.v3"
  version = "3.0.1"
