# Default values for pg_deployment in SDX.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# The values is for the namespace and the postgresql cluster name
ccpimage: crunchy-postgres-ha
ccpimageprefix: registry.developers.crunchydata.com/crunchydata
ccpimagetag: centos8-12.9-4.5.5
namespace: pgo
pgclustername: hippo
pgoimageprefix: registry.developers.crunchydata.com/crunchydata
pgoversion: 4.5.5
hipposecretuser: "hippo"
hipposecretpassword: "Supersecurepassword*"
postgressecretuser: "postgres"
postgressecretpassword: "Anothersecurepassword*"
primaryusersecretuser: "primaryuser"
primaryusersecretpassword: "Moresecurepassword*"