apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pgbackups.cr.client-go.k8s.io
spec:
  group: cr.client-go.k8s.io
  names:
    kind: Pgbackup
    listKind: PgbackupList
    plural: pgbackups
    singular: pgbackup
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pgclusters.cr.client-go.k8s.io
spec:
  group: cr.client-go.k8s.io
  names:
    kind: Pgcluster
    listKind: PgclusterList
    plural: pgclusters
    singular: pgcluster
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pgpolicies.cr.client-go.k8s.io
spec:
  group: cr.client-go.k8s.io
  names:
    kind: Pgpolicy
    listKind: PgpolicyList
    plural: pgpolicies
    singular: pgpolicy
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pgreplicas.cr.client-go.k8s.io
spec:
  group: cr.client-go.k8s.io
  names:
    kind: Pgreplica
    listKind: PgreplicaList
    plural: pgreplicas
    singular: pgreplica
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pgtasks.cr.client-go.k8s.io
spec:
  group: cr.client-go.k8s.io
  names:
    kind: Pgtask
    listKind: PgtaskList
    plural: pgtasks
    singular: pgtask
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pgupgrades.cr.client-go.k8s.io
spec:
  group: cr.client-go.k8s.io
  names:
    kind: Pgupgrade
    listKind: PgupgradeList
    plural: pgupgrades
    singular: pgupgrade
  scope: Namespaced
  version: v1
