###
#
# Copyright Â© 2017-2025 Crunchy Data Solutions, Inc. All Rights Reserved.
#
###

# config file version
apiVersion: 1

datasources:
  - name: PROMETHEUS
    type: prometheus
    access: proxy
    url: http://$PROM_HOST:$PROM_PORT
    isDefault: True
    editable: False
    orgId: 1
    version: 1
