COImagePrefix:  crunchydata
COImageTag:  centos7-2.6
DbDatabase:  userdb
DbUser:  postgres
DbPort:  5432
TableToLoad:  JSON_COLLECTION
FilePath:  sample.json
FileType:  json
PVCName:  crunchy-pvc
SecurityContext:  
