COImagePrefix:  crunchydata
COImageTag:  centos7-3.2.0
DbDatabase:  userdb
DbUser:  postgres
DbPort:  5432
TableToLoad:  JSON_COLLECTION
FilePath:  sample.json
FileType:  json
PVCName:  csv-pvc
SecurityContext:  
