COImagePrefix:  crunchydata
COImageTag:  centos7-3.2.0
DbDatabase:  userdb
DbUser:  postgres
DbPort:  5432
TableToLoad:  xraycsvtable
FilePath:  sample.csv
FileType:  csv
PVCName:  csv-pvc
SecurityContext:  
