kind: Component
images:
- name: image-pgadmin
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4
  newTag: ubi9-9.8-2550
- name: image-pgbackrest
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest
  newTag: ubi9-2.56.0-2550
- name: image-pgbouncer
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer
  newTag: ubi9-1.25-2550
- name: image-postgres-exporter
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter
  newTag: ubi9-0.18.1-2550
- name: image-postgres-operator-6.0
  newName: registry.developers.crunchydata.com/crunchydata/postgres-operator
  newTag: ubi9-6.0.0-0
- name: image-postgres-operator-5.8
  newName: registry.developers.crunchydata.com/crunchydata/postgres-operator
  newTag: ubi9-5.8.6-0
- name: image-crunchy-postgres-15
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres
  newTag: ubi9-15.15-2550
- name: image-crunchy-postgres-16
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres
  newTag: ubi9-16.11-2550
- name: image-crunchy-postgres-17
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres
  newTag: ubi9-17.7-2550
- name: image-crunchy-postgres-18
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres
  newTag: ubi9-18.1-2550
- name: image-crunchy-upgrade
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-upgrade
  newTag: ubi9-18.1-2550
- name: image-crunchy-postgres-15-gis-3.3
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-15.15-3.3-2550
- name: image-crunchy-postgres-16-gis-3.3
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-16.11-3.3-2550
- name: image-crunchy-postgres-16-gis-3.4
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-16.11-3.4-2550
- name: image-crunchy-postgres-17-gis-3.4
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-17.7-3.4-2550
- name: image-crunchy-postgres-17-gis-3.5
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-17.7-3.5-2550
- name: image-crunchy-postgres-17-gis-3.6
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-17.7-3.6-2550
- name: image-crunchy-postgres-18-gis-3.6
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-18.1-3.6-2550
