---
kubernetes_context: ""
kubernetes_in_cluster: "false"
openshift_host: ""

backrest_aws_s3_key: ""
backrest_aws_s3_secret: ""
backrest_aws_s3_bucket: ""
backrest_aws_s3_endpoint: ""
backrest_aws_s3_region: ""
backrest_port: "2022"
service_type: "ClusterIP"
default_container_resources: ""
default_load_resources: ""
default_rmdata_resources: ""
default_backup_resources: ""
default_pgbouncer_resources: ""

cleanup: "false"
common_name: "crunchydata"
crunchy_debug: "false"
enable_crunchyadm: "false"
disable_replica_start_fail_reinit: "false"

pgo_client_install: "true"
pgo_client_container_install: "false"
pgo_cluster_admin: "false"
pgo_disable_tls: "false"
pgo_tls_no_verify: "false"
pgo_disable_eventing: "false"
pgo_apiserver_port: 8443
pgo_tls_ca_store: ""
pgo_add_os_ca_store: "false"
pgo_noauth_routes: ""
pgo_apiserver_url: "https://postgres-operator"
pgo_client_cert_secret: "pgo.tls"
pgo_image_pull_secret: ""
pgo_image_pull_secret_manifest: ""

namespace: ""

delete_operator_namespace: "false"
delete_watched_namespaces: "false"
delete_metrics_namespace: "false"
preserve_pg_clusters: "false"
