---
kubernetes_context: ""
kubernetes_in_cluster: "false"
openshift_host: ""

backrest_aws_s3_key: ""
backrest_aws_s3_secret: ""
backrest_aws_s3_bucket: ""
backrest_aws_s3_endpoint: ""
backrest_aws_s3_region: ""
backrest_port: "2022"
service_type: "ClusterIP"
default_container_resources: ""
default_load_resources: ""
default_lspvc_resources: ""
default_rmdata_resources: ""
default_backup_resources: ""
default_pgbouncer_resources: ""
default_pgpool_resources: ""

cleanup: "false"
common_name: "crunchydata"
crunchy_debug: "false"

pgo_client_install: "true"
pgo_cluster_admin: "false"
pgo_disable_tls: "false"
pgo_tls_no_verify: "false"
pgo_disable_eventing: "false"
pgo_apiserver_port: 8443

delete_operator_namespace: "false"
delete_watched_namespaces: "false"
delete_metrics_namespace: "false"
preserve_pg_clusters: "false"
