apiVersion: v2
name: postgres-operator
description: Crunchy PostgreSQL Operator Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: 4.6.0
home: https://github.com/CrunchyData/postgres-operator
icon: https://github.com/CrunchyData/postgres-operator/raw/master/crunchy_logo.png
keywords:
    - PostgreSQL
    - Operator
    - Database
    - Postgres
    - SQL
    - NoSQL
    - RDBMS
