apiVersion: v2
name: postgres-operator
description: 'PGO: The Postgres Operator from Crunchy Data Helm Chart for Kubernetes'
type: application
version: 0.1.0
appVersion: 4.5.2
home: https://github.com/CrunchyData/postgres-operator
icon: https://github.com/CrunchyData/postgres-operator/raw/master/docs/static/logos/pgo.svg
keywords:
    - PostgreSQL
    - Operator
    - Database
    - Postgres
    - SQL
    - NoSQL
    - RDBMS