apiVersion: v2
name: postgres-operator-monitoring
description: Install for Crunchy PostgreSQL Operator Monitoring
type: application
version: 0.1.0
appVersion: 4.5.2
home: https://github.com/CrunchyData/postgres-operator
icon: https://github.com/CrunchyData/postgres-operator/raw/master/docs/static/pgo.svg
