---
# ======================
# Installer Controls
# ======================
fullnameOverride: ""

# rbac: settings for deployer RBAC creation
rbac:
    # rbac.create: if false RBAC resources should be in place
    create: true
    # rbac.useClusterAdmin: creates a ClusterRoleBinding giving cluster-admin to serviceAccount.name
    useClusterAdmin: false

# serviceAccount: settings for Service Account used by the deployer
serviceAccount:
    # serviceAccount.create: Whether to create a Service Account or not
    create: true
    # serviceAccount.name: The name of the Service Account to create or use
    name: ""

# the image prefix and tag to use for the 'pgo-deployer' container
pgo_image_prefix: "registry.developers.crunchydata.com/crunchydata"
pgo_image_tag: "centos8-4.6.1"

# =====================
# Configuration Options
# More info for these options can be found in the docs
# https://access.crunchydata.com/documentation/postgres-operator/latest/installation/metrics/metrics-configuration/
# =====================
alertmanager_custom_config: ""
alertmanager_custom_rules_config: ""
alertmanager_install: "true"
alertmanager_log_level: "info"
alertmanager_port: "9093"
alertmanager_service_name: "crunchy-alertmanager"
alertmanager_service_type: "ClusterIP"
alertmanager_storage_access_mode: "ReadWriteOnce"
alertmanager_storage_class_name: ""
alertmanager_supplemental_groups: ""
alertmanager_volume_size: "1Gi"
create_rbac: "true"
db_port: "5432"
delete_metrics_namespace: "false"
disable_fsgroup: "false"
grafana_admin_password: "admin"
grafana_admin_username: "admin"
grafana_dashboards_custom_config: ""
grafana_datasources_custom_config: ""
grafana_install: "true"
grafana_port: "3000"
grafana_service_name: "crunchy-grafana"
grafana_service_type: "ClusterIP"
grafana_storage_access_mode: "ReadWriteOnce"
grafana_storage_class_name: ""
grafana_supplemental_groups: ""
grafana_volume_size: "1Gi"
metrics_image_pull_secret: ""
metrics_image_pull_secret_manifest: ""
metrics_namespace: "pgo"
pgbadgerport: "10000"
prometheus_custom_config: ""
prometheus_install: "true"
prometheus_port: "9090"
prometheus_service_name: "crunchy-prometheus"
prometheus_service_type: "ClusterIP"
prometheus_storage_access_mode: "ReadWriteOnce"
prometheus_storage_class_name: ""
prometheus_supplemental_groups: ""
prometheus_volume_size: "1Gi"
