---
- name: Set output directory fact
  set_fact:
    prom_output_dir: "{{ ansible_env.HOME }}/.pgo/{{ metrics_namespace }}/output"
  tags: always

- name: Ensure output directory exists
  file: 
    path: "{{ prom_output_dir }}"
    state: directory
    mode: 0700
  tags: always

- name: Use kubectl or oc
  set_fact:
    kubectl_or_oc: "{{ openshift_oc_bin if openshift_oc_bin is defined else 'kubectl' }}"
  tags: always

- name: Deploy Prometheus
  block:
    - name: Template Prometheus RBAC
      template:
        src: "{{ item }}"
        dest: "{{ prom_output_dir }}/{{ item | replace('.j2', '') }}"
        mode: '0600'
      with_items:
      - prometheus-rbac.json.j2
      tags: [install-metrics]
      when: create_rbac|bool

    - name: Create Prometheus RBAC
      command: "{{ kubectl_or_oc }} create -f {{ prom_output_dir }}/{{ item }} -n {{ metrics_namespace }}"
      with_items:
      - prometheus-rbac.json
      tags: [install-metrics]
      when: create_rbac|bool

    - name: Create CCP Image Pull Secret
      shell: >
        {{ kubectl_or_oc }} -n {{ metrics_namespace }} get secret/{{ ccp_image_pull_secret }} -o jsonpath='{""}' 2> /dev/null ||
        {{ kubectl_or_oc }} -n {{ metrics_namespace }} create -f {{ ccp_image_pull_secret_manifest }}
      tags: [install-metrics]
      when:
        - create_rbac | bool
        - ccp_image_pull_secret_manifest != ''

    - name: Template Prometheus Objects
      template:
        src: "{{ item }}"
        dest: "{{ prom_output_dir }}/{{ item | replace('.j2', '') }}"
        mode: '0600'
      with_items: 
      - prometheus-config.yaml.j2
      - prometheus-pvc.json.j2
      - prometheus-service.json.j2
      - prometheus-deployment.json.j2
      tags: [install-metrics]

    - name: Create Prometheus Objects
      command: "{{ kubectl_or_oc }} create -f {{ prom_output_dir }}/{{ item }} -n {{ metrics_namespace }}"
      with_items:
      - prometheus-config.yaml
      - prometheus-pvc.json
      - prometheus-service.json
      - prometheus-deployment.json
      tags: [install-metrics]
