{{ $_ := set . "deployAction" "uninstall-metrics" }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pgo-metrics-deploy
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "postgres-operator.labels" . | indent 4 }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
{{ template "deployerJob.spec" . }}
